export const TABLE_RESIZE = '@TABLE/RESIZE_COL';
export const TABLE_CHANGE_TEXT = '@TABLE/CHANGE_TEXT';
export const APPLY_CELL_STYLE = '@TABLE/APPLY_CELL_STYLE';
export const CURRENT_CELL_STYLES = '@TABLE/CURRENT_CELL_STYLE';
export const CHANGE_TITLE = '@HEADER/CHANGE_TITLE';
